[package]
name = "net"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "Network middleware"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
xous = { path = "../../xous-rs" }
xous-ipc = {path="../../xous-ipc"}
log-server = { path = "../log-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {path = "../susres"}
#rkyv = "0.7.18"
rkyv = {version = "0.4.3", features = ["const_generics"], default-features = false}
llio = {path = "../llio"}
com = {path = "../com"}
byteorder = { version = "1.0", default-features = false }
trng = {path = "../trng"}
com_rs-ref = {path = "../../imports/com_rs-ref"}
modals = {path = "../modals"}
locales = {path = "../../locales"}

# for automatic SSID management and AP list storage
pddb = {path = "../pddb"}

[dependencies.smoltcp]
# ugh. we startd pulling in smoltcp as they were just fixing a bunch of bugs and getting ready for a 0.8.0 release.
# this is the last commit that doesn't break things for Xous. They pulled in some random crate that isn't compatible
# with Xous in the commit after this -- we need to look into this and maybe send a PR so we can try to work with
# the latest smoltcp. But later...let's just get things even working first with what we have.
git = "https://github.com/smoltcp-rs/smoltcp.git"
rev = "35e833e33dfd3e4efc3eb7d5de06bec17c54b011"
#path = "../../../smoltcp"
#features = ["verbose"]
#version = "0.7.5"
#features = ["proto-ipv4"]


[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
renode-minimal = []
default = []
