[package]
name = "usb-test"
version = "0.1.0"
authors = ["bunnie <bunnie@kosagi.com>"]
edition = "2018"
description = "USB test & development stub"

# Dependency policy: fully specify dependencies to the minor version number
[dependencies]
xous = { path = "../../xous-rs" }
log-server = { path = "../log-server" }
ticktimer-server = { path = "../ticktimer-server" }
xous-names = { path = "../xous-names" }
log = "0.4.14"
num-derive = {version = "0.3.3", default-features = false}
num-traits = {version = "0.2.14", default-features = false}
susres = {path = "../susres"}
keyboard = {path = "../keyboard"}
bitfield = "0.13.2"
vcell = "0.1.3"

usbd-human-interface-device = "0.1.1"
embedded-time = "0.12.1" # required by the keyboard interface

[dependencies.usb-device]
# see top level Cargo.toml for patch.crates-io directive to help with dev work
version = "0.2.8"
features=["log"]

[dev-dependencies]
rand = "0.7.3"
rand_chacha = "0.3.1"

[target.'cfg(not(any(windows,unix)))'.dependencies]
utralib = { path = "../../utralib"}

[features]
default = []
